// The point of semantic tokens here is the thing a TextMate grammar structurally cannot do:
// colour an identifier according to the instruction set the file actually includes. `bl` is the
// canonical case — a register in x86, a branch-with-link instruction in aarch64 — and a grammar
// has to pick one answer for the whole language.

import * as assert from 'assert';
import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { URI } from 'vscode-uri';
import { getSemanticTokens, SEMANTIC_TOKENS_LEGEND } from '../src/features/semanticTokens';
import { Dialect } from '../src/types';
import { Workspace } from '../src/workspace';

interface DecodedToken {
  line: number;
  word: string;
  type: string;
}

/** Reverses the LSP delta encoding back into concrete words, so the assertions below read as what
 * a user would actually see rather than as integer offsets. */
function decode(text: string, ws: Workspace, uri: string, dialect: Dialect): DecodedToken[] {
  const data = getSemanticTokens(ws, uri, dialect, text).data;
  const lines = text.split(/\r?\n/);
  const out: DecodedToken[] = [];
  let line = 0;
  let char = 0;

  for (let i = 0; i < data.length; i += 5) {
    line += data[i];
    char = data[i] === 0 ? char + data[i + 1] : data[i + 1];
    out.push({ line, word: lines[line].substr(char, data[i + 2]), type: SEMANTIC_TOKENS_LEGEND.tokenTypes[data[i + 3]] });
  }
  return out;
}

function typeOf(tokens: DecodedToken[], word: string): string | undefined {
  return tokens.find((t) => t.word.toLowerCase() === word.toLowerCase())?.type;
}

describe('getSemanticTokens', () => {
  describe('a plain x86 file', () => {
    const text = 'format binary\nuse32\nstart:\n\tmov bl, 1\n\tint 80h\n\tjmp start\n';
    const uri = 'file:///x86.asm';
    const ws = new Workspace();
    ws.updateDocument(uri, 1, text, 'fasm2');
    const tokens = decode(text, ws, uri, 'fasm2');

    it('colours x86 mnemonics as keywords', () => {
      assert.strictEqual(typeOf(tokens, 'mov'), 'keyword');
      assert.strictEqual(typeOf(tokens, 'int'), 'keyword');
      assert.strictEqual(typeOf(tokens, 'jmp'), 'keyword');
    });

    it('colours `bl` as a register, because in x86 that is what it is', () => {
      assert.strictEqual(typeOf(tokens, 'bl'), 'variable');
    });

    it('does not colour ordinary labels, leaving them to the grammar', () => {
      assert.strictEqual(typeOf(tokens, 'start'), undefined);
    });
  });

  describe('a file whose include graph supplies a non-x86 instruction set', () => {
    let tmpDir: string;

    beforeEach(async () => {
      tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'fasm2-studio-semtok-'));
    });

    afterEach(async () => {
      await fs.rm(tmpDir, { recursive: true, force: true });
    });

    async function aarch64LikeProject(source: string): Promise<{ ws: Workspace; uri: string; text: string }> {
      const mnemonics = ['bl', 'b', 'mov', 'adrp', 'svc', ...Array.from({ length: 40 }, (_, i) => `zzq${i}`)];
      const pkg =
        mnemonics.map((m) => `macro ${m} a*, b*\nend macro\n`).join('') +
        'repeat 31, i:0\n    element x#i : myreg + (i shl 0)\nend repeat\n';
      await fs.writeFile(path.join(tmpDir, 'myisa.inc'), pkg, 'utf8');

      const fsPath = path.join(tmpDir, 'prog.asm');
      await fs.writeFile(fsPath, source, 'utf8');
      const uri = URI.file(fsPath).toString();
      const ws = new Workspace();
      ws.updateDocument(uri, 1, source, 'fasm2');
      return { ws, uri, text: source };
    }

    it('colours `bl` as an instruction, the opposite of what it means in x86', async () => {
      const src = "format binary\ninclude 'myisa.inc'\n\tbl x0, x1\n";
      const { ws, uri, text } = await aarch64LikeProject(src);
      const tokens = decode(text, ws, uri, 'fasm2');

      assert.strictEqual(typeOf(tokens, 'bl'), 'macro', 'expected the package\'s own instruction, not an x86 register');
    });

    it('colours registers generated by the package\'s own repeat/element block', async () => {
      const src = "format binary\ninclude 'myisa.inc'\n\tmov x0, x1\n";
      const { ws, uri, text } = await aarch64LikeProject(src);
      const tokens = decode(text, ws, uri, 'fasm2');

      assert.strictEqual(typeOf(tokens, 'x0'), 'variable');
      assert.strictEqual(typeOf(tokens, 'x1'), 'variable');
    });

    it('does not colour x86 registers, which do not exist on this CPU', async () => {
      const src = "format binary\ninclude 'myisa.inc'\n\tmov eax, rax\n";
      const { ws, uri, text } = await aarch64LikeProject(src);
      const tokens = decode(text, ws, uri, 'fasm2');

      assert.strictEqual(typeOf(tokens, 'eax'), undefined);
      assert.strictEqual(typeOf(tokens, 'rax'), undefined);
    });

    it('does not colour an x86 mnemonic this package does not define', async () => {
      const src = "format binary\ninclude 'myisa.inc'\n\tcpuid\n";
      const { ws, uri, text } = await aarch64LikeProject(src);
      const tokens = decode(text, ws, uri, 'fasm2');

      assert.strictEqual(typeOf(tokens, 'cpuid'), undefined);
    });
  });

  describe('position sensitivity', () => {
    it('colours a mnemonic after a label on the same line', () => {
      const text = 'format binary\nstart: mov eax, 1\n';
      const uri = 'file:///label.asm';
      const ws = new Workspace();
      ws.updateDocument(uri, 1, text, 'fasm2');

      assert.strictEqual(typeOf(decode(text, ws, uri, 'fasm2'), 'mov'), 'keyword');
    });

    it('does not colour a mnemonic-spelled name used as an operand', () => {
      // A data label may legitimately be spelled like an instruction; lighting it up as one
      // wherever it is merely referenced would be actively misleading.
      const text = 'format binary\n\tmov eax, inc\n';
      const uri = 'file:///operand.asm';
      const ws = new Workspace();
      ws.updateDocument(uri, 1, text, 'fasm2');
      const tokens = decode(text, ws, uri, 'fasm2');

      assert.strictEqual(typeOf(tokens, 'mov'), 'keyword');
      assert.strictEqual(typeOf(tokens, 'inc'), undefined, 'expected the operand not to be coloured as an instruction');
    });
  });

  it('emits a well-formed delta encoding (five integers per token, never a negative delta)', () => {
    const text = 'format binary\n\tmov eax, 1\n\tint 80h\n\n\tjmp $\n';
    const uri = 'file:///encoding.asm';
    const ws = new Workspace();
    ws.updateDocument(uri, 1, text, 'fasm2');
    const data = getSemanticTokens(ws, uri, 'fasm2', text).data;

    assert.strictEqual(data.length % 5, 0);
    for (let i = 0; i < data.length; i += 5) {
      assert.ok(data[i] >= 0, 'line delta must be non-negative');
      assert.ok(data[i + 1] >= 0, 'character delta must be non-negative');
      assert.ok(data[i + 2] > 0, 'length must be positive');
      assert.ok(data[i + 3] < SEMANTIC_TOKENS_LEGEND.tokenTypes.length, 'token type must be in the legend');
    }
  });

  it('returns nothing for a document the workspace does not know, rather than throwing', () => {
    const ws = new Workspace();
    assert.deepStrictEqual(getSemanticTokens(ws, 'file:///unknown.asm', 'fasm2', 'mov eax, 1\n').data.length % 5, 0);
  });
});
