// The two pieces of an attach session that are decided before gdb is ever spoken to: what is being
// attached to, and — for a core dump — what killed the program, which gdb only ever says in prose.
import * as assert from 'assert';
import { parseTerminationSignal, resolveAttachTarget } from '../src/attachTarget';

/** Narrows the result union, so a test asserting on a target doesn't silently pass on an error. */
function target(result: ReturnType<typeof resolveAttachTarget>) {
  assert.ok(!('error' in result), `expected a target, got error: ${'error' in result ? result.error : ''}`);
  return result.target;
}

function error(result: ReturnType<typeof resolveAttachTarget>): string {
  assert.ok('error' in result, 'expected an error, got a target');
  return result.error;
}

describe('resolveAttachTarget', () => {
  it('takes a numeric processId as a live process', () => {
    assert.deepStrictEqual(target(resolveAttachTarget({ processId: 4321 })), { kind: 'process', processId: 4321 });
  });

  // VS Code substitutes a "${command:...}" process picker as a *string*, and hand-written
  // launch.json entries are quoted about as often as not.
  it('takes a stringified processId, which is what a picker substitution produces', () => {
    assert.deepStrictEqual(target(resolveAttachTarget({ processId: ' 4321 ' })), { kind: 'process', processId: 4321 });
  });

  it('takes a coreFile as a post-mortem target', () => {
    assert.deepStrictEqual(target(resolveAttachTarget({ coreFile: '/tmp/core.123' })), { kind: 'core', coreFile: '/tmp/core.123' });
  });

  // Not a preference to resolve silently: a pid and a core file describe two different debugging
  // sessions, and picking either one answers a question about the wrong program.
  it('refuses a config naming both, rather than quietly preferring one', () => {
    assert.match(error(resolveAttachTarget({ processId: 12, coreFile: '/tmp/core' })), /not both/i);
  });

  it('says what is missing when neither is given', () => {
    assert.match(error(resolveAttachTarget({})), /processId.*coreFile|coreFile.*processId/i);
  });

  it('treats an empty processId as absent rather than as the number zero', () => {
    assert.match(error(resolveAttachTarget({ processId: '' })), /needs "processId"/i);
  });

  // launch.json values arrive typed `any`; without this they reach gdb as "-target-attach NaN".
  for (const bad of ['not-a-pid', 0, -1, 1.5, '12abc']) {
    it(`rejects ${JSON.stringify(bad)} instead of passing it to gdb`, () => {
      assert.match(error(resolveAttachTarget({ processId: bad as number | string })), /positive integer/i);
    });
  }
});

describe('parseTerminationSignal', () => {
  // The exact line gdb writes to its console stream when a core dump is loaded — captured from a
  // real session against a real core, since there is no MI field carrying it.
  it('reads the signal and its meaning out of gdb\'s core-load console output', () => {
    const output = [
      'Reading symbols from ./crash...\n',
      '(No debugging symbols found in ./crash)\n',
      'Core was generated by `./crash\'.\n',
      'Program terminated with signal SIGSEGV, Segmentation fault.\n',
    ].join('');
    assert.deepStrictEqual(parseTerminationSignal(output), { name: 'SIGSEGV', meaning: 'Segmentation fault' });
  });

  it('reads a signal whose name carries digits', () => {
    assert.deepStrictEqual(parseTerminationSignal('Program terminated with signal SIGRT32, Real-time event 32.'), {
      name: 'SIGRT32',
      meaning: 'Real-time event 32',
    });
  });

  // A core taken from a healthy process (gcore, or gdb's generate-core-file before any fault) has
  // no termination signal at all — the session still has to open, just without one to report.
  it('returns nothing when the core records no signal', () => {
    assert.strictEqual(parseTerminationSignal('Core was generated by `./spin\'.\n'), undefined);
  });

  it('returns nothing for empty output', () => {
    assert.strictEqual(parseTerminationSignal(''), undefined);
  });
});
